name: Upload Website

on:
  push:
    branches:
    - main
    paths:
    - 'my-app/**'

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Packages
      run: npm install
      
    - name: Build page
      run: npm run build
      working-directory: ./my-app
      
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::335908724754:role/S3-Role
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: us-east-1 # use your region here.

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./my-app/build/ s3://gmorini.org